var express = require("express");
const router = express.Router();
const userController = require("../api/userController");
const categoryController = require("../api/categoryController");
const productController = require("../api/productController");
const orderController = require("../api/orderController");
const stockController = require("../api/stockController");
const { validate,signupvalidate } = require("../utils/validation");
const validation = require("../utils/validationSchema");
router.get("/", function (req, res, next) {
  res.send("welcome to adminPanel");
});
router.post("/signup",validate(validation.usersignup),userController.addUser);
router.post("/google",validate(validation.googleAuth),userController.googleAuth);
router.get("/signup",userController.viewUsers);
router.put("/signup/:id",userController.editUsers);
router.delete("/signup/:id",userController.deleteUsers);
router.post("/login", validate(validation.signin), userController.login);
router.post("/category",categoryController.addCategory);
router.get("/category",categoryController.viewCategory);
router.put("/category/:id",categoryController.editCategory);
router.post("/category",categoryController.addCategory);
router.post("/searchCategory",categoryController.searchCategory);
router.get("/product",productController.viewProduct);
router.put("/product/:id",productController.editProduct);
router.post("/searchProduct",productController.searchProduct);
router.post("/order",orderController.addOrder);
router.get("/order",orderController.viewTotalOrder);
router.post("/filter",orderController.filterOrder);
router.post("/searchOrder",orderController.searchOrder);
router.post("/stock",stockController.addStock);
router.get("/stock",stockController.viewStock);
router.post("/searchStock",stockController.searchStock);
router.post("/searchStockId",stockController.searchStockId);
router.put("/stock/:id",stockController.editStock);
router.delete("/stock/:id",stockController.deleteStock);
module.exports = router;
